version: "3.8"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - IMAGE_TAG_GATEWAY_ALPINE
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./gateway:/usr/src/gateway
    environment:
      - ACCOUNT_DB_TYPE=postgres
      - ACCOUNT_DB_HOST=account_tag_db
      - ACCOUNT_DB_PORT=${ACCOUNT_POSTGRES_PORT}
      - ACCOUNT_DB_USERNAME=${ACCOUNT_POSTGRES_USER}
      - ACCOUNT_DB_PASSWORD=${ACCOUNT_POSTGRES_PASSWORD}
      - ACCOUNT_DB_DATABASE=${ACCOUNT_POSTGRES_DATABASE}
      - TAG_DB_TYPE=postgres
      - TAG_DB_HOST=account_tag_db
      - TAG_DB_PORT=${TAG_POSTGRES_PORT}
      - TAG_DB_USERNAME=${TAG_POSTGRES_USER}
      - TAG_DB_PASSWORD=${TAG_POSTGRES_PASSWORD}
      - TAG_DB_DATABASE=${TAG_POSTGRES_DATABASE}
      - CHALLENGE_DB_TYPE=mongodb
      - CHALLENGE_DB_HOST=challenge_db
      - CHALLENGE_DB_PORT=${CHALLENGE_MONGODB_PORT}
      - CHALLENGE_DB_USERNAME=${CHALLENGE_MONGODB_USER}
      - CHALLENGE_DB_PASSWORD=${CHALLENGE_MONGODB_PASSWORD}
      - CHALLENGE_DB_DATABASE=${CHALLENGE_MONGODB_DATABASE}
    depends_on:
      - account_tag_db
      - challenge_db
    container_name: ${GATEWAY_CONTAINER_NAME}
  account_tag_db:
    image: "postgres:${IMAGE_TAG_POSTGRES}"
    ports:
      - ${ACCOUNT_POSTGRES_PORT}:${ACCOUNT_POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${ACCOUNT_POSTGRES_ROOT_USER}
      - POSTGRES_PASSWORD=${ACCOUNT_POSTGRES_ROOT_PASSWORD}
    volumes: 
      - ./.docker/account_tag_db:/var/lib/postgresql/data
      - ./.docker/postgres-scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
  challenge_db:
    image: "mongo:${IMAGE_TAG_MONGO}"
    ports:
      - ${CHALLENGE_MONGODB_PORT}:${CHALLENGE_MONGODB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${CHALLENGE_MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${CHALLENGE_MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${CHALLENGE_MONGODB_DATABASE}
    volumes:
      - ./.docker/challenge_db:/data/db
    command: mongod --auth
  pgadmin:
    image: dpage/pgadmin4:${IMAGE_TAG_PGADMIN}
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD} 
        PGADMIN_LISTEN_PORT: 80
    ports:
        - ${PGADMIN_PORT}:80
    volumes:
        - ./.docker/pgadmin:/var/lib/pgadmin
    depends_on:
        - account_tag_db 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${CHALLENGE_MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${CHALLENGE_MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: challenge_db
    depends_on:
      - challenge_db

